### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by JVThomas** [learn-co-curriculum/angular-using-directive-controllers-lab#3]
Package.json file is missing so I had to create my own in order to install necessary dependencies through npm. 

If you're a fellow student, just copy, paste, and save the code snippet below to package.json

```
{
   "name": "angular",
   "version": "1.0.0",
   "devDependencies": {
     "express": "^4.13.4"
   }
}
```

Feel free to close the comment if the issue is addressed.

**Comment by AnnJohn** [comment]
hi @JVThomas thanks for catching this. We've updated the lab.
